[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
bright_foreground = "#eeeeee"
foreground = "#bdc1c6"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "regular"

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 1.0

[mouse]
bindings = [
{ mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
{ key = "PageUp",   mods = "Shift",   action = "ScrollPageUp"   },
{ key = "PageDown", mods = "Shift",   action = "ScrollPageDown" },
{ key = "End",      mods = "Shift",   action = "ScrollToBottom" },
{ key = "Home",     mods = "Shift",   action = "ScrollToTop"    },
{ key = "Up",     mods = "Control|Shift",   action = "ScrollLineUp"    },
{ key = "Down",     mods = "Control|Shift",   action = "ScrollLineDown"    },
]
[selection]
save_to_clipboard = true
