services:
  dev:
    build:
      context: .
      args:
        UID: 1000
        GRP: 1000
    container_name: emacs_nvim_tmux
    restart: always
    volumes:
      - ./app:/app:z
      - node_modules:/app/node_modules
      - dotlocal:/home/app/.local
      - emacs_eln-cache:/home/app/.config/emacs/eln-cache
      - ./emacs_recentf:/home/app/.config/emacs/emacs_recentf:z
      - ./projectile-bookmarks.eld:/home/app/.config/emacs/projectile-bookmarks.eld:z
      - ./emacs_sessions:/home/app/.config/emacs/sessions:z
    stdin_open: true
    tty: true
    user: 1000:1000
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR:
        /home/app/.config/zsh
        #    security_opt:  #This this if copying to system clipboard fails.  Needed with moby engine but not Docker proper.
        #      - label:type:container_runtime_t
volumes:
  dotlocal:
  node_modules:
  emacs_eln-cache:
  emacs_elpa:
