services:
  dev:
    build:
      context: .
      args:
        UID: 1000
        GRP: 1000
    container_name: emacs_nvim_tmux
    restart: always
    volumes:
      - ./app:/app:z
      - ./zettelkasten:/home/app/Documents/zettelkasten:z
      - dotlocal:/home/app/.local
      - dotfiles_dir:/home/app/.dotfiles
      - nvim_dir:/home/app/.config/nvim
    stdin_open: true
    tty: true
    user: 1000:1000
    ports:
      - "22:22"
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR:
        /home/app/.config/zsh
        #    security_opt:  #This this if copying to system clipboard fails.  Needed with moby engine but not Docker proper.
        #      - label:type:container_runtime_t
volumes:
  dotlocal:
  dotfiles_dir:
  nvim_dir:
